### ISSUE TITLE
Lol server icon stoled from samsung j series wallpaper

### ISSUE THREAD

**Issue by marohinmark** [jostroOS/assets#1]

**Comment by ghost** [comment]
No, it's not, we simply used the same font. Additionally, if you look on some of the accent wallpapers, the J clearly has an additional curvature and line sticking out of the top of it.
Go back to playing COD, kid.

**Comment by F-fengzi** [comment]
lmao just searched up what samsung j series is

and btw we're not using the same font

**Comment by F-fengzi** [comment]
ya know what, go register a trademark on every single letter, then you can go sue literally every company

![F59E0D25-32CB-42EF-91A9-06D310252DC7](https://user-images.githubusercontent.com/41763546/136624771-6f604b8a-067f-426d-9ed3-ce0b9b512607.jpeg)

**Comment by NoozAbooz** [comment]
~~mmmm yes we use wallpaper of 2015 Samsung phone series for our logo, even though our whole dev team simps for xiaomi~~

**Comment by ghost** [comment]
did someone mention xiaomi?

**Comment by ghost** [comment]
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

**Comment by F-fengzi** [comment]
stop it...

**Comment by marohinmark** [comment]
social credit +999

**Comment by marohinmark** [comment]
did u say '"The Tiananmen Square protests of 1989"? social credit -99999999

**Comment by NoozAbooz** [comment]
> 动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 言論 思想 反共 反革命 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 激流中國 北京之春 大紀元時報 九評論共産黨 獨裁 專制 壓制 統一 監視 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 活摘器官 誘拐 買賣人口 遊進 走私 毒品 賣淫 春畫 賭博 六合彩 天安門 天安门 法輪功 李洪志 Winnie the Pooh 劉曉波动态网自由门

"Nobel peace prize"

**Comment by marohinmark** [comment]
anyways, this issue is a joke

**Comment by dan2wik** [comment]
when you

**Comment by dan2wik** [comment]
skunchk

**Comment by dan2wik** [comment]
t
